### ISSUE TITLE
Create Student class with following property.

### ISSUE THREAD

**Issue by pankajsoft** [ayush-prog/Opps-Study#2]
Class having following properties:

ID
Last Name
First Name
E-mail Address
Student ID
Level
Room
Date of Birth
ID Number
Home Phone
Mobile Phone
Address
City
State/Province
ZIP/Postal Code
Country/Region
Web Page
Notes
Attachments
Special Circumstances
Physician Name
Physician Phone Number
Allergies
Medications
Insurance Carrier
Insurance Number

**Comment by ayush-prog** [comment]
Class with following properties is created
